import type { ConnectorDescriptor } from "./types";

const checkedAt = "2026-08-12";
const redistributableTermsCheckedAt = "2026-08-13";

export const connectorCatalog: ConnectorDescriptor[] = [
  {
    id: "un-comtrade",
    name: "UN Comtrade",
    publisher: "United Nations Statistics Division",
    officialUri: "https://comtradeplus.un.org/",
    documentationUri: "https://uncomtrade.org/docs/un-comtrade-api/",
    termsUri: "https://comtradeplus.un.org/LicenseAgreement",
    checkedAt,
    runtime: "remote",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "optional_api_key",
    allowedHosts: ["comtradeapi.un.org"],
    minimumIntervalMs: 1_000,
    maxResponseBytes: 25_000_000,
    boundary: "Official reported merchandise/service trade; mirror asymmetry, revisions, gaps, and classification changes remain material.",
    licenseNotes: ["API access does not grant blanket redistribution rights; raw payloads are never bundled."],
    operationalNotes: ["Preview access is limited; free and premium subscription quotas differ."],
  },
  {
    id: "oecd-icio",
    name: "OECD Inter-Country Input-Output tables",
    publisher: "OECD",
    officialUri: "https://www.oecd.org/en/data/datasets/inter-country-input-output-tables.html",
    documentationUri: "https://www.oecd.org/en/data/insights/data-explainers/2024/09/api.html",
    termsUri: "https://www.oecd.org/en/about/terms-conditions.html",
    checkedAt,
    runtime: "remote",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "none",
    allowedHosts: ["sdmx.oecd.org", "stats.oecd.org"],
    minimumIntervalMs: 1_000,
    maxResponseBytes: 100_000_000,
    boundary: "Balanced country-industry accounts, not company supplier relationships or current operational flows.",
    licenseNotes: ["Users accept OECD terms when retrieving data; the repository stores queries and hashes."],
    operationalNotes: ["Large TiVA spaces are rate limited; bulk partitions are preferred over unbounded API requests."],
  },
  {
    id: "sec-edgar",
    name: "SEC EDGAR data APIs",
    publisher: "U.S. Securities and Exchange Commission",
    officialUri: "https://data.sec.gov/",
    documentationUri: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    termsUri: "https://www.sec.gov/about/privacy-information/security-policy",
    checkedAt,
    runtime: "remote",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "ENTITY_REPORTED",
    auth: "none",
    allowedHosts: ["data.sec.gov", "www.sec.gov"],
    minimumIntervalMs: 110,
    maxResponseBytes: 100_000_000,
    boundary: "Issuer/fund filings and XBRL facts are entity-reported and may omit operational relationships.",
    licenseNotes: ["Government-created SEC content and issuer filing content have different authorship; raw archives are not bundled."],
    operationalNotes: ["Declare a real user agent and remain below the SEC fair-access ceiling of 10 requests per second."],
  },
  {
    id: "gleif",
    name: "GLEIF LEI API",
    publisher: "Global Legal Entity Identifier Foundation",
    officialUri: "https://www.gleif.org/en/lei-data/gleif-api/",
    documentationUri: "https://documenter.getpostman.com/view/7679680/SVYrrxuU",
    termsUri: "https://www.gleif.org/en/meta/lei-data-terms-of-use",
    checkedAt: redistributableTermsCheckedAt,
    runtime: "remote",
    redistributionMode: "redistributable",
    rawRedistributable: true,
    evidenceGrade: "THIRD_PARTY_VERIFIED",
    auth: "none",
    allowedHosts: ["api.gleif.org"],
    minimumIntervalMs: 250,
    maxResponseBytes: 25_000_000,
    boundary: "Legal-entity identity and reported accounting relationships are not commercial supply relationships.",
    redistributionLicense: { name: "CC0 1.0 Universal", spdx: "CC0-1.0" },
    licenseNotes: ["GLEIF provides LEI and LE-RD through the Access Service under CC0 1.0; do not imply GLEIF endorsement or affiliation."],
    operationalNotes: ["Ignore unknown response fields and prefer current plural successor relationships."],
  },
  {
    id: "faostat",
    name: "FAOSTAT",
    publisher: "Food and Agriculture Organization of the United Nations",
    officialUri: "https://www.fao.org/faostat/en/",
    documentationUri: "https://www.fao.org/faostat/en/#data",
    termsUri: "https://www.fao.org/contact-us/terms/db-terms-of-use/en",
    checkedAt: redistributableTermsCheckedAt,
    runtime: "remote",
    redistributionMode: "redistributable",
    rawRedistributable: true,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "none",
    allowedHosts: ["bulks-faostat.fao.org", "fenixservices.fao.org", "files-faostat.fao.org"],
    minimumIntervalMs: 500,
    maxResponseBytes: 100_000_000,
    boundary: "Country-reported agricultural statistics differ in coverage and quality; third-party datasets may carry exceptions.",
    redistributionLicense: { name: "Creative Commons Attribution 4.0 International", spdx: "CC-BY-4.0" },
    licenseNotes: ["Default CC BY 4.0 applies unless dataset metadata states a third-party or other exception."],
    operationalNotes: ["A release must retain FAO attribution and the dataset-specific metadata record."],
  },
  {
    id: "openfda-drug-shortages",
    name: "openFDA Drug Shortages",
    publisher: "U.S. Food and Drug Administration",
    officialUri: "https://open.fda.gov/apis/drug/drugshortages/",
    documentationUri: "https://open.fda.gov/apis/drug/drugshortages/",
    termsUri: "https://open.fda.gov/terms/",
    checkedAt: redistributableTermsCheckedAt,
    runtime: "remote",
    redistributionMode: "redistributable",
    rawRedistributable: true,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "optional_api_key",
    allowedHosts: ["api.fda.gov"],
    minimumIntervalMs: 250,
    maxResponseBytes: 25_000_000,
    boundary: "U.S. shortage records are not a global supply graph and must not be used for individual medical decisions.",
    redistributionLicense: { name: "Public Domain / CC0 1.0 Universal", spdx: "CC0-1.0" },
    licenseNotes: ["The Drug Shortages catalog is marked Public Domain and CC0; retain FDA attribution and do not imply endorsement."],
    operationalNotes: ["Current standard quotas differ with and without a free API key."],
  },
  {
    id: "ofac-sls",
    name: "OFAC Sanctions List Service",
    publisher: "U.S. Department of the Treasury, OFAC",
    officialUri: "https://ofac.treasury.gov/sanctions-list-service",
    documentationUri: "https://ofac.treasury.gov/sanctions-list-service",
    termsUri: "https://home.treasury.gov/utility/terms-and-conditions",
    checkedAt,
    runtime: "remote",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "none",
    allowedHosts: ["sanctionslistservice.ofac.treas.gov", "ofac.treasury.gov"],
    minimumIntervalMs: 500,
    maxResponseBytes: 100_000_000,
    boundary: "OFAC designations cover OFAC-administered programs only; the connector is not a legal compliance determination.",
    licenseNotes: ["Official hashes should be retained where available; the repository does not republish full lists."],
    operationalNotes: ["SLS publishes current files, customizable datasets, and archived deltas."],
  },
  {
    id: "world-bank-wits",
    name: "World Bank WITS API",
    publisher: "World Bank",
    officialUri: "https://wits.worldbank.org/witsapiintro.aspx?lang=en",
    documentationUri: "https://wits.worldbank.org/data/public/WITSAPI_UserGuide.pdf",
    termsUri: "https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets",
    checkedAt,
    runtime: "remote",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "OFFICIAL_OBSERVED",
    auth: "none",
    allowedHosts: ["wits.worldbank.org"],
    minimumIntervalMs: 500,
    maxResponseBytes: 25_000_000,
    boundary: "Trade/tariff indicators are aggregated and constrained by the selected source, nomenclature, and query dimensions.",
    licenseNotes: ["Underlying providers may impose terms in addition to World Bank dataset terms."],
    operationalNotes: ["The API rejects whole-database queries; bounded dimensions and cached partitions are mandatory."],
  },
  {
    id: "unctad-lsci",
    name: "UNCTAD Liner Shipping Connectivity Index",
    publisher: "UN Trade and Development and MDS Transmodal",
    officialUri: "https://unctadstat.unctad.org/insights/theme/246",
    documentationUri: "https://unctad.org/news/new-context-calls-changing-how-we-measure-maritime-connectivity",
    termsUri: "https://unctad.org/terms-use",
    checkedAt,
    runtime: "import_only",
    redistributionMode: "download_on_run",
    rawRedistributable: false,
    evidenceGrade: "THIRD_PARTY_VERIFIED",
    auth: "user_file",
    allowedHosts: [],
    minimumIntervalMs: 0,
    maxResponseBytes: 100_000_000,
    boundary: "The published index is not the underlying carrier schedule or AIS dataset, and methodology revisions affect comparability.",
    licenseNotes: ["MDS Transmodal underlying data rights are not presumed redistributable."],
    operationalNotes: ["Import a user-downloaded UNCTAD export with its metadata; no undocumented endpoint is scraped."],
  },
  {
    id: "imf-portwatch",
    name: "IMF PortWatch",
    publisher: "International Monetary Fund and University of Oxford",
    officialUri: "https://portwatch.imf.org/",
    documentationUri: "https://www.imf.org/en/news/articles/2023/11/13/pr23390-imf-university-oxford-launch-portwatch-platform-simulate-trade-disruptions",
    termsUri: "https://www.imf.org/external/terms.htm",
    checkedAt,
    runtime: "import_only",
    redistributionMode: "user_provided",
    rawRedistributable: false,
    evidenceGrade: "THIRD_PARTY_VERIFIED",
    auth: "user_file",
    allowedHosts: [],
    minimumIntervalMs: 0,
    maxResponseBytes: 100_000_000,
    boundary: "PortWatch indicators and simulations do not expose a complete firm/product supply network and may rely on third-party satellite/AIS inputs.",
    licenseNotes: ["Only user-provided lawful exports are imported; no platform data are bundled."],
    operationalNotes: ["Import metadata must identify export time, fields, and applicable terms."],
  },
];

export function connectorById(id: string): ConnectorDescriptor {
  const connector = connectorCatalog.find((item) => item.id === id);
  if (!connector) throw new Error(`Unknown connector ${id}.`);
  return connector;
}
