export const capabilityCatalog = [
  {
    id: "system-mapping",
    label: "System mapping",
    shortLabel: "Map",
    group: "analysis",
    description: "Translate a decision problem into typed nodes, dependencies, and explicit boundaries.",
  },
  {
    id: "uncertainty-bounds",
    label: "Uncertainty bounds",
    shortLabel: "Bounds",
    group: "analysis",
    description: "Keep known, verified, and assumed relationships in separate result envelopes.",
  },
  {
    id: "constrained-optimization",
    label: "Constrained optimization",
    shortLabel: "Optimize",
    group: "analysis",
    description: "Compare feasible choices under budget, timing, capacity, and reversibility constraints.",
  },
  {
    id: "sensitivity-analysis",
    label: "Sensitivity analysis",
    shortLabel: "Sensitivity",
    group: "analysis",
    description: "Test whether a decision survives changes in declared shock and propagation assumptions.",
  },
  {
    id: "temporal-reasoning",
    label: "Temporal reasoning",
    shortLabel: "Time",
    group: "analysis",
    description: "Separate event time, knowledge time, intervention lead time, and outcome windows.",
  },
  {
    id: "data-systems",
    label: "Data systems",
    shortLabel: "Data",
    group: "engineering",
    description: "Preserve schemas, identifiers, lineage, licenses, and conservative transformations.",
  },
  {
    id: "reproducible-computation",
    label: "Reproducible computation",
    shortLabel: "Recompute",
    group: "engineering",
    description: "Package inputs and outputs so another person can recompute or reject the result.",
  },
  {
    id: "evidence-governance",
    label: "Evidence governance",
    shortLabel: "Evidence",
    group: "decision",
    description: "Prevent citations, inferences, simulations, and outcomes from silently changing status.",
  },
  {
    id: "stakeholder-communication",
    label: "Stakeholder communication",
    shortLabel: "Communicate",
    group: "decision",
    description: "Turn technical uncertainty into a bounded question, trade-off, and decision gate.",
  },
  {
    id: "public-interest-ethics",
    label: "Public-interest ethics",
    shortLabel: "Ethics",
    group: "decision",
    description: "Make distributional effects, safety limits, accountability, and affected groups visible.",
  },
  {
    id: "financial-risk",
    label: "Financial risk",
    shortLabel: "Finance",
    group: "domain",
    description: "Reason about concentration, liquidity, mandate constraints, and fiduciary trade-offs.",
  },
  {
    id: "health-informatics",
    label: "Health informatics",
    shortLabel: "Health IT",
    group: "domain",
    description: "Examine terminology, interoperability, workflow, decision support, and population reporting.",
  },
  {
    id: "behavioral-experimentation",
    label: "Behavioral experimentation",
    shortLabel: "Behavior",
    group: "domain",
    description: "Separate measurement, assignment, mechanism, heterogeneous response, and rollout evidence.",
  },
  {
    id: "spatial-policy",
    label: "Spatial and place policy",
    shortLabel: "Place",
    group: "domain",
    description: "Connect location, access, housing, infrastructure, institutions, and place-based outcomes.",
  },
  {
    id: "resilience-operations",
    label: "Resilience operations",
    shortLabel: "Resilience",
    group: "domain",
    description: "Compare buffers, diversification, routing, allocation, and staged recovery choices.",
  },
] as const;

export type CapabilityId = (typeof capabilityCatalog)[number]["id"];

export interface CaseDecisionProfile {
  decisionOwner: string;
  stakeholders: string[];
  capabilities: CapabilityId[];
  methods: string[];
  userTasks: string[];
  tradeoffs: string[];
  guardrail: string;
}

export const decisionProfiles: Record<string, CaseDecisionProfile> = {
  "suez-route-restress": {
    decisionOwner: "Cross-border operations lead",
    stakeholders: ["carriers", "procurement teams", "production planners", "downstream customers"],
    capabilities: ["system-mapping", "uncertainty-bounds", "constrained-optimization", "temporal-reasoning", "stakeholder-communication", "resilience-operations"],
    methods: ["bitemporal eligibility", "missing-graph bounds", "lead-time-constrained Pareto analysis"],
    userTasks: ["compare buffer and rerouting bundles", "locate the dependency that drives the upper bound", "state the evidence needed before acting"],
    tradeoffs: ["speed versus normalized cost", "continuity versus reliance on assumed links"],
    guardrail: "Do not interpret the stress index as vessel delay, revenue loss, or a forecast of a closure.",
  },
  "semiconductor-capacity-restress": {
    decisionOwner: "Technology manufacturing planner",
    stakeholders: ["fabrication partners", "component engineers", "assembly teams", "customers"],
    capabilities: ["system-mapping", "constrained-optimization", "data-systems", "evidence-governance", "stakeholder-communication", "resilience-operations"],
    methods: ["branch-and-merge topology", "bounded propagation", "feasible bundle enumeration"],
    userTasks: ["compare inventory, redesign, and allocation", "trace where two dependency branches merge", "explain why feasibility is not a recommendation"],
    tradeoffs: ["inventory cost versus qualification lead time", "allocation continuity versus customer coverage"],
    guardrail: "No company, fabrication site, production volume, or realized shortage is represented.",
  },
  "medical-ppe-demand-restress": {
    decisionOwner: "Public-health supply coordinator",
    stakeholders: ["health workers", "care sites", "distributors", "patients"],
    capabilities: ["uncertainty-bounds", "constrained-optimization", "stakeholder-communication", "public-interest-ethics", "temporal-reasoning", "resilience-operations"],
    methods: ["demand-shock compilation", "access-oriented criticality weighting", "bounded intervention comparison"],
    userTasks: ["compare stockpiling, supplier diversity, and prioritization", "surface who bears a shortage", "write a safety-limited decision boundary"],
    tradeoffs: ["aggregate continuity versus equitable allocation", "rapid prioritization versus evidence quality"],
    guardrail: "The case is neither clinical guidance nor an emergency-allocation recommendation.",
  },
  "ukraine-commodity-compound-restress": {
    decisionOwner: "Food and energy resilience analyst",
    stakeholders: ["producers", "logistics operators", "public agencies", "households"],
    capabilities: ["system-mapping", "uncertainty-bounds", "constrained-optimization", "public-interest-ethics", "stakeholder-communication", "resilience-operations"],
    methods: ["compound-shock compilation", "cycle-safe fixed point", "Pareto frontier analysis"],
    userTasks: ["separate direct from propagated pressure", "compare reserve and substitution bundles", "identify distributional questions the model cannot answer"],
    tradeoffs: ["system continuity versus affordability", "reserve use versus longer-horizon resilience"],
    guardrail: "No country-level price, food-security, or welfare effect is estimated.",
  },
  "panama-drought-restress": {
    decisionOwner: "Network and route planner",
    stakeholders: ["canal operators", "carriers", "importers", "regional producers"],
    capabilities: ["temporal-reasoning", "sensitivity-analysis", "spatial-policy", "stakeholder-communication", "uncertainty-bounds", "resilience-operations"],
    methods: ["dynamic edge activation", "horizon comparison", "shock-transmission sensitivity"],
    userTasks: ["find when diversification overtakes buffering", "inspect the mid-horizon topology change", "communicate a reversible trigger"],
    tradeoffs: ["short-run inventory versus long-run route diversity", "regional access versus added transport burden"],
    guardrail: "The graph does not reconstruct vessel queues, water levels, tolls, or actual cargo volumes.",
  },
  "red-sea-rerouting-restress": {
    decisionOwner: "Global logistics risk lead",
    stakeholders: ["ship operators", "cargo owners", "production sites", "delivery recipients"],
    capabilities: ["system-mapping", "temporal-reasoning", "sensitivity-analysis", "stakeholder-communication", "uncertainty-bounds", "resilience-operations"],
    methods: ["dynamic edge expiry", "upper-bound stress comparison", "lead-time analysis"],
    userTasks: ["compare routing and inventory assumptions", "locate the effect of an expiring link", "set a review trigger for changing course"],
    tradeoffs: ["route continuity versus longer transit", "faster action versus uncertain intervention effect"],
    guardrail: "No freight-rate, emissions, insurance, or realized delivery-time effect is claimed.",
  },
  "baltimore-port-restress": {
    decisionOwner: "Regional infrastructure coordinator",
    stakeholders: ["port operators", "workers", "manufacturers", "nearby communities", "cargo owners"],
    capabilities: ["system-mapping", "spatial-policy", "public-interest-ethics", "constrained-optimization", "stakeholder-communication", "resilience-operations"],
    methods: ["place-based dependency mapping", "access-loss scenario", "budget-constrained option comparison"],
    userTasks: ["compare alternate gateways and inland buffers", "name affected groups outside the supply chain", "separate engineering facts from scenario assumptions"],
    tradeoffs: ["regional continuity versus burden shifting", "speed of rerouting versus local capacity"],
    guardrail: "This is not an engineering reconstruction or an estimate of the incident's realized losses.",
  },
  "refining-hurricane-restress": {
    decisionOwner: "Essential-services continuity lead",
    stakeholders: ["refiners", "freight operators", "public agencies", "essential-service providers", "residents"],
    capabilities: ["temporal-reasoning", "constrained-optimization", "public-interest-ethics", "stakeholder-communication", "uncertainty-bounds", "resilience-operations"],
    methods: ["capacity-shock compilation", "criticality-weighted outcomes", "reserve and rerouting frontier"],
    userTasks: ["compare reserves, rerouting, and demand management", "test whether a bundle fits the lead-time window", "surface service-equity questions"],
    tradeoffs: ["commercial continuity versus essential-service priority", "reserve depletion versus immediate access"],
    guardrail: "The case is not a weather forecast or a fuel-market impact estimate.",
  },
  "critical-minerals-export-stress": {
    decisionOwner: "Strategic technology policy analyst",
    stakeholders: ["material processors", "manufacturers", "infrastructure operators", "public agencies"],
    capabilities: ["system-mapping", "evidence-governance", "constrained-optimization", "public-interest-ethics", "stakeholder-communication", "resilience-operations"],
    methods: ["policy-restriction scenario", "concentration stress", "value-of-information ranking"],
    userTasks: ["compare diversification with additional evidence", "identify the assumed bottleneck", "explain why context does not prove topology"],
    tradeoffs: ["strategic reserve cost versus exposure", "rapid substitution versus qualification risk"],
    guardrail: "The synthetic topology names no mineral, country, firm, or current export-control measure.",
  },
  "ofac-list-change-stress": {
    decisionOwner: "Financial-compliance operations lead",
    stakeholders: ["compliance reviewers", "payment teams", "suppliers", "customers", "legal counsel"],
    capabilities: ["data-systems", "evidence-governance", "financial-risk", "constrained-optimization", "stakeholder-communication", "public-interest-ethics"],
    methods: ["fail-closed policy stress", "queue dependency mapping", "manual-review option comparison"],
    userTasks: ["preserve the compliance gate while comparing continuity options", "separate list data from a legal conclusion", "document escalation and review ownership"],
    tradeoffs: ["transaction continuity versus compliance safety", "automation speed versus accountable review"],
    guardrail: "The case performs no sanctions screening and makes no legal or eligibility determination.",
  },
  "drug-shortage-restress": {
    decisionOwner: "Medicine access coordinator",
    stakeholders: ["manufacturers", "wholesalers", "care sites", "clinicians", "patients"],
    capabilities: ["data-systems", "uncertainty-bounds", "constrained-optimization", "public-interest-ethics", "stakeholder-communication", "resilience-operations"],
    methods: ["official-source context isolation", "care-access criticality", "bounded supply intervention analysis"],
    userTasks: ["compare buffer, alternate supply, and distribution priority", "trace a source record without treating it as a topology", "state the clinical boundary"],
    tradeoffs: ["aggregate stock versus care-site access", "speed versus evidence for alternate supply"],
    guardrail: "No current shortage record is used as topology, and no treatment recommendation is produced.",
  },
  "food-export-compound-stress": {
    decisionOwner: "Food-system policy planner",
    stakeholders: ["producers", "traders", "distributors", "public agencies", "households"],
    capabilities: ["system-mapping", "constrained-optimization", "public-interest-ethics", "sensitivity-analysis", "stakeholder-communication", "resilience-operations"],
    methods: ["compound supply-policy shock", "Pareto frontier", "affordability-oriented criticality"],
    userTasks: ["compare reserves and import diversity", "test joint-shock assumptions", "identify which groups require separate outcome data"],
    tradeoffs: ["reserve release versus future resilience", "market continuity versus household affordability"],
    guardrail: "No current production, trade, price, nutrition, or food-security observation drives the scenario.",
  },
  "health-data-interoperability-stress": {
    decisionOwner: "Health-information governance lead",
    stakeholders: ["patients", "clinicians", "health IT teams", "care organizations", "public-health analysts"],
    capabilities: ["health-informatics", "data-systems", "evidence-governance", "public-interest-ethics", "stakeholder-communication", "reproducible-computation"],
    methods: ["terminology-workflow mapping", "branch-and-merge failure analysis", "manual-review safeguard comparison"],
    userTasks: ["compare mapping validation, source redundancy, and manual review", "trace how missing semantics reach a downstream decision", "separate interoperability standards from local implementation evidence"],
    tradeoffs: ["exchange completeness versus safety review", "automation speed versus human accountability"],
    guardrail: "The case contains no patient data and makes no claim about clinical performance, certification, or deployment.",
  },
  "behavioral-intervention-evidence-stress": {
    decisionOwner: "Program evaluation lead",
    stakeholders: ["participants", "service teams", "evaluators", "program owners", "oversight bodies"],
    capabilities: ["behavioral-experimentation", "evidence-governance", "uncertainty-bounds", "reproducible-computation", "public-interest-ethics", "stakeholder-communication"],
    methods: ["measurement-to-rollout dependency map", "assignment-integrity stress", "reversible pilot comparison"],
    userTasks: ["distinguish observed behavior from mechanism", "compare measurement, randomization, and staged-rollout safeguards", "write a result statement that preserves null and heterogeneous outcomes"],
    tradeoffs: ["learning speed versus measurement quality", "population reach versus reversible experimentation"],
    guardrail: "No treatment effect, causal mechanism, participant response, or program impact is estimated.",
  },
  "place-based-regeneration-equity-stress": {
    decisionOwner: "Place-based regeneration planner",
    stakeholders: ["current residents", "housing providers", "local businesses", "transport agencies", "local government"],
    capabilities: ["spatial-policy", "public-interest-ethics", "constrained-optimization", "temporal-reasoning", "stakeholder-communication", "system-mapping"],
    methods: ["place-based dependency mapping", "phased intervention analysis", "distributional decision framing"],
    userTasks: ["compare housing, access, and local-business safeguards", "state who benefits and who bears transition costs", "set a review trigger for displacement pressure"],
    tradeoffs: ["redevelopment pace versus resident continuity", "capital delivery versus affordable access"],
    guardrail: "The case represents no named neighborhood, parcel, household, grant, or measured displacement effect.",
  },
  "portfolio-concentration-fiduciary-stress": {
    decisionOwner: "Portfolio risk committee",
    stakeholders: ["beneficiaries", "portfolio managers", "risk teams", "compliance officers", "oversight committees"],
    capabilities: ["financial-risk", "uncertainty-bounds", "constrained-optimization", "sensitivity-analysis", "evidence-governance", "stakeholder-communication"],
    methods: ["concentration-shock mapping", "liquidity and mandate constraints", "rebalancing frontier"],
    userTasks: ["compare rebalancing, liquidity buffer, and exposure review", "test sensitivity to stress transmission", "state the fiduciary and evidence limits of the output"],
    tradeoffs: ["concentration risk versus mandate tracking", "liquidity protection versus opportunity cost"],
    guardrail: "The case contains no real portfolio, security recommendation, return forecast, or evidence of fiduciary suitability.",
  },
};
